### ISSUE TITLE
Not yet compatible with SS4

### ISSUE THREAD

**Issue by RVXD** [silvershop/silvershop-comparison#10]
It seems this module it not yet updated for SS4.

ie. the class Feature has the old style class references:

`

private static $has_many = array(
        "Products" => "Product_Feature"
    );

    private static $has_one = array(
        "Group" => "FeatureGroup"
    );

    private static $belongs_many_many = array(
        "Product" => "Product"
    );`

**Comment by wilr** [comment]
SS4 upgrade is still a WIP. If you install the master branch you'll see the state of the upgrade before I finished. A bunch of things like that might still be outstanding.

**Comment by RVXD** [comment]
I am working on the module to get it working again.

**Comment by wilr** [comment]
#11
