### ISSUE TITLE
Float variable no longer valid with PHP 7 - Change to DBFloat

### ISSUE THREAD

**Issue by adrian-stein** [silvershop/silvershop-comparison#8]
The `Float `object name is reserved in PHP 7 and needs to be chanegd to `DBFloat`

[This line of codes](https://github.com/burnbright/silverstripe-shop-comparison/blob/master/code/model/Feature.php#L81)  needs to be updated to make the module still work.

**Comment by adrian-stein** [comment]
Any word on this people? @wilr  @jedateach

**Comment by wilr** [comment]
@adrian-stein Sounds good. I know they updated this in SilverStripe 3.6, would need to up the minimum requirement. Would you like to submit a PR?

**Comment by wilr** [comment]
Fixed in `1.0.0` tag

**Comment by adrian-stein** [comment]
Thanks will.
