### ISSUE TITLE
Fix SS4 install

### ISSUE THREAD

**Issue by madmatt** [silvershop/silvershop-comparison#9]
Running `composer require silvershop/comparison` on an SS4 site installs an incompatible `^1.0` version, because:

* The 1.0.0 tag requires `silvershop/core: *`
* There's no released version of the module targeting `silvershop/core: ^3`

Running `composer require silvershop/comparison dev-master` works, but requires knowing about the problem and how to fix it - otherwise you just get errors about `DataExtension` not being a valid class which take time to figure out.

If it's stable, could we get a v2.0, and update the 1.0 line to target silvershop/core <3?

I'd make the pull requests, but there's only a tag for the older version, and I can't make releases anyway.

**Comment by wilr** [comment]
Yo @madmatt, `1.0.1` tagged with composer set to ^1 || ^2 so it doesn't install the SS4 version. 1 branch setup to track along with that. `2.0.0` tagged.

**Comment by madmatt** [comment]
Legend, thanks @wilr!
